
name: 'Setup Node 18'
description: 'Setup Node 18'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"