name: 'Cache node_modules and artifacts'
description: 'Cache node_modules and artifacts'
runs:
  using: 'composite'
	runs-on: [ubuntu-latest]
  steps:
    - name: Cache node_modules
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          */*/node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-lerna-${{ hashFiles('package-lock.json', '**/package-lock.json') }}-dependencies
    - name: Cache artifacts
      id: cache-artifacts
      uses: actions/cache@v3
      with:
        path: |
          packages/*/dist
          packages/core/build
        key: ${{ runner.os }}-lerna-${{ github.run_id }}-artifacts
