name: deploy-alpha

concurrency: alpha

on:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: alpha
    steps: 
      - uses: actions/checkout@v2
        with: ${{ github.event.workflow_run.head_branch }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm ci
      - name: Version And Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NEXT_PUBLIC_SEGMENT_KEY: JfTfmHaATChc4xueS7RcCBsixI71dJIJ
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          lerna version prerelease --preid alpha --exact --yes
          npm run publish:alpha
