name: test

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm i
      - name: List all dependencies
        shell: bash
        run: npm list
      - name: Build essential packages used by others
        run: npm run build-essential

  unit-tests:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm i
      - name: List all dependencies
        shell: bash
        run: npm list
      - name: Build essential packages used by others
        run: npm run build-essential
      - name: Running functional and unit tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          REPO_URL: ${{ secrets.REPO_URL }}
          wroom_endpoint: ${{ secrets.PRISMIC_URL }}
          authentication_server_endpoint: ${{ secrets.AUTHENTICATION_SERVER_ENDPOINT }}
          customtypesapi_endpoint: ${{ secrets.CUSTOMTYPESAPI_ENDPOINT }}
          user_service_endpoint: ${{ secrets.USER_SERVICE_ENDPOINT }}
          acl_provider_endpoint: ${{ secrets.ACL_PROVIDER_ENDPOINT }}
        run: lerna run test
  
  dep-check:
    needs: build
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Dependency Checks
        run: npm run depcheck
  
  prettier:
    needs: build
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Prettier
        run: npm run prettier:check
  
  linting:
    needs: build
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Linting
        run: lerna run lint

  audit:
    needs: build
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Audit
        run: lerna run audit

  build-init:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Build slice machine init
        working-directory: ./packages/init
        run: npm run build

  build-ui:
    needs: build
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Build and export slice machine UI
        working-directory: ./packages/slice-machine
        run: npm run build && npm run export-build

  e2e-tests:
    needs: build
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/restore-cache
      - uses: ./.github/actions/setup-node
      - name: Running End to End tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PRISMIC_URL: ${{ secrets.PRISMIC_URL }}
          wroom_endpoint: ${{ secrets.PRISMIC_URL }}
          authentication_server_endpoint: ${{ secrets.AUTHENTICATION_SERVER_ENDPOINT }}
          customtypesapi_endpoint: ${{ secrets.CUSTOMTYPESAPI_ENDPOINT }}
          user_service_endpoint: ${{ secrets.USER_SERVICE_ENDPOINT }}
          acl_provider_endpoint: ${{ secrets.ACL_PROVIDER_ENDPOINT }}
        run: npm i && npm run test:e2e
