name: test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: 'packages/**/package-lock.json'
      - name: Install dependencies
        run: npm i
      - name: Build slice machine core
        working-directory: ./packages/core
        run: npm run build
      - name: Running functional and unit tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: lerna run test
      - name: Linting
        run: lerna run lint --parallel
      - name: Audit
        run: lerna run audit
      - name: Build slice machine init
        working-directory: ./packages/init
        run: npm run build
      - name: Build and export slice machine UI
        working-directory: ./packages/slice-machine
        run: npm run build && npm run export-build
      - name: Running End to End tests
        working-directory: "./packages/slice-machine/tests/project"
        run: npm i && npm run test:e2e
