name: test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-lerna-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Build essential packages used by others
        run: npm run build-essential
      - name: Running functional and unit tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          REPO_URL: ${{ secrets.REPO_URL }}
          wroom_endpoint: ${{ secrets.PRISMIC_URL }}
          authentication_server_endpoint: ${{ secrets.AUTHENTICATION_SERVER_ENDPOINT }}
          customtypesapi_endpoint: ${{ secrets.CUSTOMTYPESAPI_ENDPOINT }}
          user_service_endpoint: ${{ secrets.USER_SERVICE_ENDPOINT }}
          acl_provider_endpoint: ${{ secrets.ACL_PROVIDER_ENDPOINT }}
        run: lerna run test
      - name: Dependency Checks
        run: npm run depcheck
      - name: Prettier
        run: npm run prettier:check
      - name: Linting
        run: lerna run lint
      - name: Audit
        run: lerna run audit
      - name: Build slice machine init
        working-directory: ./packages/init
        run: npm run build
      - name: Build and export slice machine UI
        working-directory: ./packages/slice-machine
        run: npm run build && npm run export-build
      - name: Running End to End tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PRISMIC_URL: ${{ secrets.PRISMIC_URL }}
          wroom_endpoint: ${{ secrets.PRISMIC_URL }}
          authentication_server_endpoint: ${{ secrets.AUTHENTICATION_SERVER_ENDPOINT }}
          customtypesapi_endpoint: ${{ secrets.CUSTOMTYPESAPI_ENDPOINT }}
          user_service_endpoint: ${{ secrets.USER_SERVICE_ENDPOINT }}
          acl_provider_endpoint: ${{ secrets.ACL_PROVIDER_ENDPOINT }}
        run: npm i && npm run test:e2e
